mybatis:
    mapper-locations: classpath:mapper/*.xml
spring:
    datasource:
        password: 123456
        url: jdbc:mysql://localhost:3306/store?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
        username: root
    jackson:
        default-property-inclusion: NON_NULL
user:
    address:
        max-count: 20
